### ISSUE TITLE
Investigate if memory allocation can be optimized

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-processor-sdk#9]
### Feature description

This feature request comes from the following PR comment: https://github.com/ConduitIO/conduit-processor-sdk/pull/2#discussion_r1432655348. 

Summary: When memory in the WASM module is allocated and free, it's always being done with new byte slices. We should investigate if it's possible to do with a single byte slice which will be reused for all the commands and responses, to minimize the number of allocations.

**Comment by lovromazgon** [comment]
Done in #7.
